ordonnance_med_index:
    path:     /
    defaults: { _controller: "hostooSanteBundle:Ordonnance:index" }
    methods:  GET

ordonnance_med_show:
    path:     /{id}/show
    defaults: { _controller: "hostooSanteBundle:Ordonnance:show" }
    methods:  GET

ordonnance_med_print:
    path:     /{id}/print
    defaults: { _controller: "hostooSanteBundle:Ordonnance:printOrdonnance" }
    methods:  GET

ordonnance_med_new:
    path:     /new/{id}
    defaults: { _controller: "hostooSanteBundle:Ordonnance:new" }
    methods:  [GET, POST]
ordonnance_med_newnrs:
    path:     /newNrs/{id}
    defaults: { _controller: "hostooSanteBundle:Ordonnance:newNrs" }
    methods:  [GET, POST]


ordonnance_med_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooSanteBundle:Ordonnance:edit" }
    methods:  [GET, POST]

ordonnance_med_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooSanteBundle:Ordonnance:delete" }
    methods:  DELETE
