symptomes_index:
    path:     /
    defaults: { _controller: "hostooSanteBundle:Symptomes:index" }
    methods:  GET

symptomes_show:
    path:     /{id}/show
    defaults: { _controller: "hostooSanteBundle:Symptomes:show" }
    methods:  GET

symptomes_new:
    path:     /new
    defaults: { _controller: "hostooSanteBundle:Symptomes:new" }
    methods:  [GET, POST]

symptomes_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooSanteBundle:Symptomes:edit" }
    methods:  [GET, POST]

symptomes_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooSanteBundle:Symptomes:delete" }
    methods:  DELETE
