<?php

namespace hostoo\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NonUniqueResultException;
use Doctrine\ORM\NoResultException;

/**
 * ClotureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClotureRepository extends EntityRepository
{
    public function testOuverture($user,$date)
    {
        $req=$this->createQueryBuilder('a');
        $req->join('a.caisse','cais')->where('cais.id = :user')
            ->andWhere('a.dateouverture LIKE :ladat')
            ->setParameter('user', $user)
            ->setParameter('ladat', $date.'%');

            return $req->getQuery()->getOneOrNullResult();

    }
}
