<?php

namespace hostoo\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComissionRepository extends EntityRepository
{
}
