<?php

namespace hostoo\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * rapportCaisseJrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class rapportCaisseJrRepository extends EntityRepository
{
    public function rapportToday()
    {
        $qb=$this->createQueryBuilder('a');
        $qb
            ->where('a.daterap LIKE :datec')
            ->setParameter('datec',date('Y-m-d').'%')
        ->orderBy('a.id');

        return $qb->getQuery()->getResult();
    }

    public function rapportHierSomme()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.report) as reps, SUM(a.depenseusd) as depusd,  SUM(a.depensecdf) as depcdf, SUM(a.recettenet) as recnet, SUM(a.recettebrute) as recbrt')
            ->where('a.daterap LIKE :datec')
            ->setParameter('datec',date('Y-m-d',strtotime('-1 day')).'%')
            ->orderBy('a.id');

        return $qb->getQuery()->getResult();
    }

    public function trouverLeReport($rep,$date)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.daterap LIKE :datec')
            ->andWhere('a.report=:report')
            ->setParameter('datec',$date.'%')
            ->setParameter('report',$rep)
            ;

        return $qb->getQuery()->setMaxResults(1)->getOneOrNullResult();
    }

    public function lesMoisRAP()
    {
        $qb=$this->createQueryBuilder('a');
        $qb
            ->where('a.daterap LIKE :datec')
            ->setParameter('datec',date('Y-m-d').'%')
            ->orderBy('a.id');

        return $qb->getQuery()->getResult();
    }


    public function rapportMonth($annee,$mois)
    {
        $qb=$this->createQueryBuilder('a');
        $qb
            ->where('a.daterap LIKE :datec')
            ->setParameter('datec',$annee.'-'.$mois.'%')
            ->orderBy('a.id');

        return $qb->getQuery()->getResult();
    }
}
