anamnese_index:
    path:     /
    defaults: { _controller: "hostooSanteBundle:Anamnese:index" }
    methods:  GET

anamnese_show:
    path:     /{id}/show
    defaults: { _controller: "hostooSanteBundle:Anamnese:show" }
    methods:  GET

anamnese_new:
    path:     /new/{id}
    defaults: { _controller: "hostooSanteBundle:Anamnese:new" }
    methods:  [GET, POST]

anamnese_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooSanteBundle:Anamnese:edit" }
    methods:  [GET, POST]

anamnese_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooSanteBundle:Anamnese:delete" }
    methods:  DELETE
