antecedent_index:
    path:     /
    defaults: { _controller: "hostooSanteBundle:Antecedent:index" }
    methods:  GET

antecedent_show:
    path:     /{id}/show
    defaults: { _controller: "hostooSanteBundle:Antecedent:show" }
    methods:  GET

antecedent_new:
    path:     /new
    defaults: { _controller: "hostooSanteBundle:Antecedent:new" }
    methods:  [GET, POST]

antecedent_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooSanteBundle:Antecedent:edit" }
    methods:  [GET, POST]

antecedent_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooSanteBundle:Antecedent:delete" }
    methods:  DELETE

antecedent_patient:
    path:     /{pat}/sesantecedents
    defaults: { _controller: "hostooSanteBundle:Antecedent:antecedentPatient" }
    methods:  [GET, POST]