examensphysiques_index:
    path:     /
    defaults: { _controller: "hostooSanteBundle:ExamensPhysiques:index" }
    methods:  GET

examensphysiques_show:
    path:     /{id}/show
    defaults: { _controller: "hostooSanteBundle:ExamensPhysiques:show" }
    methods:  GET

examensphysiques_new:
    path:     /new/{id}
    defaults: { _controller: "hostooSanteBundle:ExamensPhysiques:new" }
    methods:  [GET, POST]

examensphysiques_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooSanteBundle:ExamensPhysiques:edit" }
    methods:  [GET, POST]

examensphysiques_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooSanteBundle:ExamensPhysiques:delete" }
    methods:  DELETE
