<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActesRepository extends EntityRepository
{
    public function actesInfirmiers()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.categories=1 or a.categories=2 or a.categories=3')
            ->orderBy('a.id','asc');
        return $qb->getQuery()->getResult();
    }
}
