<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BSCaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BSCaisseRepository extends EntityRepository
{
    public function TotalDepensesUSD()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.montant)')
            ->where('a.devise LIKE :devise')
            ->setParameter('devise','USD')
        ;
        return $qb->getQuery()->getSingleResult();
    }
    public function depensesDayUSD()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.montant)')
        ->where('a.datebs LIKE :datec and a.devise LIKE :devise')
        ->setParameter('datec',date('Y-m-d').'%')
            ->setParameter('devise','USD')
        ;
        return $qb->getQuery()->getSingleResult();
    }
    public function depensesMoisUSD($mois,$annee)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.montant) as depmois')
            ->where('a.datebs LIKE :datec')
            ->setParameter('datec',$annee.'-'.$mois.'%')
        ;
        return $qb->getQuery()->getResult();
    }

    public function depensesDayCDF()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.montant)')
            ->where('a.datebs LIKE :datec and a.devise LIKE :devise')
            ->setParameter('datec',date('Y-m-d').'%')
            ->setParameter('devise','CDF')
        ;
        return $qb->getQuery()->getSingleResult();
    }

    public function depensesMoisCDF()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.montantCdf) as depmois')
            ->where('a.datebs LIKE :datec')
            ->setParameter('datec','%'.date('m-Y').'%')
        ;
        return $qb->getQuery()->getResult();
    }
}
