<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CattarifsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CattarifsRepository extends EntityRepository
{
    public function leurConvention($nb)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->join('a.actes','b')
            ->join('b.actes','t')
            ->join('t.convention','c')
            ->where('c.id = :conv')
            ->setParameter('conv',$nb);
        return $qb->getQuery()->getResult();
    }
}
