<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdonnanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdonnanceRepository extends EntityRepository
{
    public function dateStock($datea)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('a')
            ->where('a.dateordo LIKE :datea')
            ->andWhere('a.livre=:pin')
            ->setParameter('datea',$datea)
            ->setParameter('pin',1)
        ;

        return $req->getQuery()->getResult();
    }
}
