<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OrdonnanceImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrdonnanceImgRepository extends EntityRepository
{

    public function examensDemandesMois()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('COUNT(ex) as total')
            ->join('a.actes','ex')
            ->where('a.dateordo LIKE :datec')
            ->setParameter('datec',date('Y-m').'%');

        return $qb->getQuery()->getSingleResult();
    }

    public function examensDemandesMoisL()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('a')
            ->where('a.dateordo LIKE :datec')
            ->setParameter('datec',date('Y-m').'%');

        return $qb->getQuery()->getResult();
    }

    public function examensDuJour()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateordo LIKE :datec')
            ->setParameter('datec',date('Y-m-d').'%');

        return $qb->getQuery()->getResult();

    }

    public function examensNRMois()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('(COUNT(ex)-COUNT(res)) as total')
            ->join('a.actes','ex')
            ->join('a.resultat','res')
            ->where('a.dateordo LIKE :datec')
            ->setParameter('datec',date('Y-m').'%');

        return $qb->getQuery()->getSingleResult();

    }

    public function examensNRMoisL()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('a')
            ->join('a.actes','ex')
            ->join('a.resultat','res')
            ->where('a.dateordo LIKE :datec')
            ->andWhere('a.resultat = :rec')
            ->setParameter('datec',date('Y-m').'%')
            ->setParameter('rec',null)
        ;

        return $qb->getQuery()->getResult();

    }

    public function examensRMois()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('COUNT(res) as total')
            ->join('a.actes','ex')
            ->join('a.resultat','res')
            ->where('a.dateordo LIKE :datec')
            ->setParameter('datec',date('Y-m').'%');

        return $qb->getQuery()->getSingleResult();

    }

    public function examensRMoisL()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('res')
            ->join('a.actes','ex')
            ->join('a.resultat','res')
            ->where('a.dateordo LIKE :datec')
            ->setParameter('datec',date('Y-m').'%');

        return $qb->getQuery()->getResult();

    }
}
