<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ResultatsImgRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultatsImgRepository extends EntityRepository
{
    public function examensDemandesMois()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('COUNT(a) as total')
            ->where('a.dateresultat LIKE :datec')
            ->setParameter('datec',date('Y-m').'%');

        return $qb->getQuery()->getSingleResult();
    }

    public function examensDemandesMoisL()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('a')
            ->where('a.dateresultat LIKE :datec')
            ->setParameter('datec',date('Y-m').'%');

        return $qb->getQuery()->getResult();
    }

    public function examensDuJour()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateresultat LIKE :datec')
            ->setParameter('datec',date('Y-m-d').'%');

        return $qb->getQuery()->getResult();

    }

    public function examensNRMois()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('COUNT(a) as total')
            ->where('a.dateresultat LIKE :datec')
            ->andWhere('a.attente = :att')
            ->setParameter('datec',date('Y-m').'%')
            ->setParameter('att',0);

        return $qb->getQuery()->getSingleResult();

    }

    public function examensNRMoisL()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('a')
            ->join('a.resultat','res')
            ->where('a.dateresultat LIKE :datec')
            ->setParameter('datec',date('Y-m').'%')
            ->setParameter('rec',null)
        ;

        return $qb->getQuery()->getResult();

    }

    public function examensRMois()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('COUNT(a) as total')
            ->where('a.dateresultat LIKE :datec')
            ->setParameter('datec',date('Y-m').'%');

        return $qb->getQuery()->getSingleResult();

    }

    public function examensRMoisL()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('res')
            ->where('a.dateresultat LIKE :datec')
            ->setParameter('datec',date('Y-m').'%');

        return $qb->getQuery()->getResult();

    }

    public function resultatsIMG($user)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('tar.designationacte as desacte, act.prix as prix')
            ->join('a.ordonnance','ord')
            ->join('a.acte','act')
            ->join('act.actes','tar')
            ->join('ord.medecin','med')
            ->where('med.id = :user')
            ->setParameter('user',$user)
        ;
        return $req->getQuery()->getResult();
    }


    public function statistiqueParActe()
    {
        $req=$this->createQueryBuilder('a');
        $req->select('(myacte.designationacte) as nom, count(a) as nbreff')
            ->join('a.acte','acte')
            ->join('acte.actes','myacte')->groupBy('myacte')
        ->where('a.attente like :ok')
        ->setParameter('ok',false);
        return $req->getQuery()->getResult();

    }

    public function statistiqueParNEActe()
    {
        $req=$this->createQueryBuilder('a');
        $req->select('(myacte.designationacte) as nom, count(a) as nbreff')
            ->join('a.acte','acte')
            ->join('acte.actes','myacte')
            ->where('a.attente like :ok')
            ->setParameter('ok',true)
            ->groupBy('myacte');
        return $req->getQuery()->getResult();

    }


}
