hostoo_sante_savepatient:
    path:     /enregistrer-patient
    defaults: { _controller: hostooSanteBundle:Patient:enregistrerPatient }

hostoo_sante_savepatientrc:
    path:     /enregistrer-patientrc
    defaults: { _controller: hostooSanteBundle:Patient:enregistrerPatientRC }
hostoo_sante_editpatientrc:
    path:     /modifier-patientrc/{id}
    defaults: { _controller: hostooSanteBundle:Patient:modifierPatientRC }

reception_t_b:
    path:     /receptionTB
    defaults: { _controller: hostooSanteBundle:TB:receptionTB }

hostoo_sante_fichepatient:
    path:     /fiche-du-patient
    defaults: { _controller: hostooSanteBundle:Patient:fichePatient }

hostoo_sante_voirpatient:
    path:     /voir-le-patient/{id}
    defaults: { _controller: hostooSanteBundle:Patient:voirPatient }
    requirements:
        id: \d+
    options:
        expose : true

hostoo_sante_listepatients:
    path:     /liste-des-patients
    defaults: { _controller: hostooSanteBundle:Patient:listePatients }

hostoo_sante_listepatientsprives:
    path:     /liste-des-patients-prives
    defaults: { _controller: hostooSanteBundle:Patient:listePatientsPrives }

hostoo_sante_listepatientsconventionnes:
    path:     /liste-des-patients-conventionnes
    defaults: { _controller: hostooSanteBundle:Patient:listePatientsConventionnes }

hostoo_sante_addtypeclient:
    path:     /typeclients
    defaults: { _controller: hostooSanteBundle:Types:ajouterTC }

hostoo_sante_addformule:
    path:     /formules
    defaults: { _controller: hostooSanteBundle:Types:ajouterFormule }

hostoo_sante_editionformule:
    path:     /formules-edition
    defaults: { _controller: hostooSanteBundle:Types:EditionFormule }

hostoo_sante_lireepisode:
    path:     /lire-un-episode/{id}
    defaults: { _controller: hostooSanteBundle:Episode:lireEpisode}

hostoo_sante_reception:
    path:     /reception
    defaults: { _controller: hostooSanteBundle:Default:reception}

hostoo_ajouter_parent:
    path:     /ajouter-dependant/{id}
    defaults: { _controller: hostooSanteBundle:Patient:ajouterParente }
    options:
        expose : true
notpatient:
    path: /notpatient/{route}
    defaults: { _controller: hostooSanteBundle:Notification:ajouterPatient }
    requirements:
        route : test
tarifs_med:
    path:     /tarifs
    defaults: { _controller: hostooSanteBundle:Actes:listeActesRC }

recherche_patient:
    path:     /recherche_patient
    defaults: { _controller: hostooSanteBundle:Default:recherchePatient }
    options:
        expose: true


#RDV
hostoo_sante_creerdv:
    path:     /creerunrdvpatient
    defaults: { _controller: hostooSanteBundle:RDV:creerUnRDVPatient }

attrib_rdv:
    path:     /attribueraumed
    defaults: { _controller: hostooSanteBundle:RDV:attribuerAuMed }