hostoo_img_dash:
    path: /dash
    defaults: { _controller: hostooSanteBundle:Imagerie:index }

ajouter_resultati:
    path: /ajouter-resultatI/{id}
    defaults: { _controller: hostooSanteBundle:Imagerie:ajouterResultat }
valider_resultati:
    path: /valider-resultatI/{id}
    defaults: { _controller: hostooSanteBundle:Imagerie:validerResultat }