<?php

namespace Proxies\__CG__\hostoo\SanteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Episode extends \hostoo\SanteBundle\Entity\Episode implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'dateepisode', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'observation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'consultation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'patient', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'utilisateur', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'factures', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'sv', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'anamnese', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'exphys', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'diag', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'ordonnance', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'ordonnancelabos', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'ordonnanceimgs', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'listesoins', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'rdvpat', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'consult'];
        }

        return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'dateepisode', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'observation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'consultation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'patient', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'utilisateur', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'factures', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'sv', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'anamnese', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'exphys', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'diag', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'ordonnance', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'ordonnancelabos', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'ordonnanceimgs', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'listesoins', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'rdvpat', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Episode' . "\0" . 'consult'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Episode $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateepisode($dateepisode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateepisode', [$dateepisode]);

        return parent::setDateepisode($dateepisode);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateepisode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateepisode', []);

        return parent::getDateepisode();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservation($observation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservation', [$observation]);

        return parent::setObservation($observation);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservation', []);

        return parent::getObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsultation($consultation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsultation', [$consultation]);

        return parent::setConsultation($consultation);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsultation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsultation', []);

        return parent::getConsultation();
    }

    /**
     * {@inheritDoc}
     */
    public function setPatient(\hostoo\SanteBundle\Entity\Patient $patient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPatient', [$patient]);

        return parent::setPatient($patient);
    }

    /**
     * {@inheritDoc}
     */
    public function getPatient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPatient', []);

        return parent::getPatient();
    }

    /**
     * {@inheritDoc}
     */
    public function setUtilisateur(\hostoo\UserBundle\Entity\Utilisateur $utilisateur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUtilisateur', [$utilisateur]);

        return parent::setUtilisateur($utilisateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getUtilisateur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUtilisateur', []);

        return parent::getUtilisateur();
    }

    /**
     * {@inheritDoc}
     */
    public function addSv(\hostoo\SanteBundle\Entity\SignesVitaux $sv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSv', [$sv]);

        return parent::addSv($sv);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSv(\hostoo\SanteBundle\Entity\SignesVitaux $sv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSv', [$sv]);

        return parent::removeSv($sv);
    }

    /**
     * {@inheritDoc}
     */
    public function getSv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSv', []);

        return parent::getSv();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnamnese(\hostoo\SanteBundle\Entity\Anamnese $anamnese = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnamnese', [$anamnese]);

        return parent::setAnamnese($anamnese);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnamnese()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnamnese', []);

        return parent::getAnamnese();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiag(\hostoo\SanteBundle\Entity\Diagnostic $diag = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiag', [$diag]);

        return parent::setDiag($diag);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiag', []);

        return parent::getDiag();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdonnance(\hostoo\SanteBundle\Entity\Ordonnance $ordonnance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdonnance', [$ordonnance]);

        return parent::addOrdonnance($ordonnance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdonnance(\hostoo\SanteBundle\Entity\Ordonnance $ordonnance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdonnance', [$ordonnance]);

        return parent::removeOrdonnance($ordonnance);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdonnance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdonnance', []);

        return parent::getOrdonnance();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdonnancelabo(\hostoo\SanteBundle\Entity\OrdonnanceLabo $ordonnancelabo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdonnancelabo', [$ordonnancelabo]);

        return parent::addOrdonnancelabo($ordonnancelabo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdonnancelabo(\hostoo\SanteBundle\Entity\OrdonnanceLabo $ordonnancelabo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdonnancelabo', [$ordonnancelabo]);

        return parent::removeOrdonnancelabo($ordonnancelabo);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdonnancelabos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdonnancelabos', []);

        return parent::getOrdonnancelabos();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrdonnanceimg(\hostoo\SanteBundle\Entity\OrdonnanceImg $ordonnanceimg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrdonnanceimg', [$ordonnanceimg]);

        return parent::addOrdonnanceimg($ordonnanceimg);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrdonnanceimg(\hostoo\SanteBundle\Entity\OrdonnanceImg $ordonnanceimg)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrdonnanceimg', [$ordonnanceimg]);

        return parent::removeOrdonnanceimg($ordonnanceimg);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrdonnanceimgs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrdonnanceimgs', []);

        return parent::getOrdonnanceimgs();
    }

    /**
     * {@inheritDoc}
     */
    public function setRdvpat(\hostoo\SanteBundle\Entity\RdvPatient $rdvpat = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRdvpat', [$rdvpat]);

        return parent::setRdvpat($rdvpat);
    }

    /**
     * {@inheritDoc}
     */
    public function getRdvpat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRdvpat', []);

        return parent::getRdvpat();
    }

    /**
     * {@inheritDoc}
     */
    public function setExphys(\hostoo\SanteBundle\Entity\ExamensPhysiques $exphys = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExphys', [$exphys]);

        return parent::setExphys($exphys);
    }

    /**
     * {@inheritDoc}
     */
    public function getExphys()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExphys', []);

        return parent::getExphys();
    }

    /**
     * {@inheritDoc}
     */
    public function addExphy(\hostoo\SanteBundle\Entity\ExamensPhysiques $exphys)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addExphy', [$exphys]);

        return parent::addExphy($exphys);
    }

    /**
     * {@inheritDoc}
     */
    public function removeExphy(\hostoo\SanteBundle\Entity\ExamensPhysiques $exphys)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeExphy', [$exphys]);

        return parent::removeExphy($exphys);
    }

    /**
     * {@inheritDoc}
     */
    public function setListesoins(\hostoo\SanteBundle\Entity\ListeSoins $listesoins = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListesoins', [$listesoins]);

        return parent::setListesoins($listesoins);
    }

    /**
     * {@inheritDoc}
     */
    public function getListesoins()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListesoins', []);

        return parent::getListesoins();
    }

    /**
     * {@inheritDoc}
     */
    public function verifierConsultation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'verifierConsultation', []);

        return parent::verifierConsultation();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function setConsult(\hostoo\SanteBundle\Entity\Consultation $consult = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConsult', [$consult]);

        return parent::setConsult($consult);
    }

    /**
     * {@inheritDoc}
     */
    public function getConsult()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConsult', []);

        return parent::getConsult();
    }

    /**
     * {@inheritDoc}
     */
    public function addFacture(\hostoo\SanteBundle\Entity\Facture $factures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFacture', [$factures]);

        return parent::addFacture($factures);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFacture(\hostoo\SanteBundle\Entity\Facture $factures)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFacture', [$factures]);

        return parent::removeFacture($factures);
    }

    /**
     * {@inheritDoc}
     */
    public function getFactures()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFactures', []);

        return parent::getFactures();
    }

    /**
     * {@inheritDoc}
     */
    public function nbActes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'nbActes', []);

        return parent::nbActes();
    }

}
