<?php

namespace Proxies\__CG__\hostoo\SanteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Facture extends \hostoo\SanteBundle\Entity\Facture implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'datefacture', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'prix', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'solde', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'urgence', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'validation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'lasolde', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'log', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'episode', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'requerant', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'hospitalisation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'commandes', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'produits', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'soldes', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'percepteur', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'visa', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'img', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'labo', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'paiements'];
        }

        return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'datefacture', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'prix', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'solde', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'urgence', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'validation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'lasolde', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'log', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'episode', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'requerant', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'hospitalisation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'commandes', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'produits', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'soldes', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'percepteur', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'visa', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'img', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'labo', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Facture' . "\0" . 'paiements'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Facture $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatefacture($datefacture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatefacture', [$datefacture]);

        return parent::setDatefacture($datefacture);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatefacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatefacture', []);

        return parent::getDatefacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrgence($urgence)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrgence', [$urgence]);

        return parent::setUrgence($urgence);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrgence()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrgence', []);

        return parent::getUrgence();
    }

    /**
     * {@inheritDoc}
     */
    public function setValidation($validation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValidation', [$validation]);

        return parent::setValidation($validation);
    }

    /**
     * {@inheritDoc}
     */
    public function getValidation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValidation', []);

        return parent::getValidation();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpisode(\hostoo\SanteBundle\Entity\Episode $episode = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpisode', [$episode]);

        return parent::setEpisode($episode);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpisode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpisode', []);

        return parent::getEpisode();
    }

    /**
     * {@inheritDoc}
     */
    public function addSolde(\hostoo\SanteBundle\Entity\Solde $soldes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addSolde', [$soldes]);

        return parent::addSolde($soldes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeSolde(\hostoo\SanteBundle\Entity\Solde $soldes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeSolde', [$soldes]);

        return parent::removeSolde($soldes);
    }

    /**
     * {@inheritDoc}
     */
    public function getSoldes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSoldes', []);

        return parent::getSoldes();
    }

    /**
     * {@inheritDoc}
     */
    public function setSolde($solde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSolde', [$solde]);

        return parent::setSolde($solde);
    }

    /**
     * {@inheritDoc}
     */
    public function getSolde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSolde', []);

        return parent::getSolde();
    }

    /**
     * {@inheritDoc}
     */
    public function resteAPayer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'resteAPayer', []);

        return parent::resteAPayer();
    }

    /**
     * {@inheritDoc}
     */
    public function setLasolde($lasolde)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLasolde', [$lasolde]);

        return parent::setLasolde($lasolde);
    }

    /**
     * {@inheritDoc}
     */
    public function getLasolde()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLasolde', []);

        return parent::getLasolde();
    }

    /**
     * {@inheritDoc}
     */
    public function addProduit(\hostoo\PharmacieBundle\Entity\Produit $produits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProduit', [$produits]);

        return parent::addProduit($produits);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProduit(\hostoo\PharmacieBundle\Entity\Produit $produits)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProduit', [$produits]);

        return parent::removeProduit($produits);
    }

    /**
     * {@inheritDoc}
     */
    public function getProduits()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProduits', []);

        return parent::getProduits();
    }

    /**
     * {@inheritDoc}
     */
    public function getActesFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActesFacture', []);

        return parent::getActesFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function setPercepteur(\hostoo\UserBundle\Entity\Utilisateur $percepteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPercepteur', [$percepteur]);

        return parent::setPercepteur($percepteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getPercepteur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPercepteur', []);

        return parent::getPercepteur();
    }

    /**
     * {@inheritDoc}
     */
    public function setHospitalisation(\hostoo\HospisBundle\Entity\Hospitalisation $hospitalisation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHospitalisation', [$hospitalisation]);

        return parent::setHospitalisation($hospitalisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getHospitalisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHospitalisation', []);

        return parent::getHospitalisation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLog($log)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLog', [$log]);

        return parent::setLog($log);
    }

    /**
     * {@inheritDoc}
     */
    public function getLog()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLog', []);

        return parent::getLog();
    }

    /**
     * {@inheritDoc}
     */
    public function setVisa(\hostoo\GestionBundle\Entity\Visa $visa = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVisa', [$visa]);

        return parent::setVisa($visa);
    }

    /**
     * {@inheritDoc}
     */
    public function getVisa()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVisa', []);

        return parent::getVisa();
    }

    /**
     * {@inheritDoc}
     */
    public function addCommande(\hostoo\GestionBundle\Entity\Commande $commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addCommande', [$commande]);

        return parent::addCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function removeCommande(\hostoo\GestionBundle\Entity\Commande $commande)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeCommande', [$commande]);

        return parent::removeCommande($commande);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommandes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommandes', []);

        return parent::getCommandes();
    }

    /**
     * {@inheritDoc}
     */
    public function setRequerant(\hostoo\SanteBundle\Entity\Requerant $requerant = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRequerant', [$requerant]);

        return parent::setRequerant($requerant);
    }

    /**
     * {@inheritDoc}
     */
    public function getRequerant()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRequerant', []);

        return parent::getRequerant();
    }

    /**
     * {@inheritDoc}
     */
    public function addImg(\hostoo\SanteBundle\Entity\OrdonnanceImg $img)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addImg', [$img]);

        return parent::addImg($img);
    }

    /**
     * {@inheritDoc}
     */
    public function removeImg(\hostoo\SanteBundle\Entity\OrdonnanceImg $img)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeImg', [$img]);

        return parent::removeImg($img);
    }

    /**
     * {@inheritDoc}
     */
    public function getImg()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImg', []);

        return parent::getImg();
    }

    /**
     * {@inheritDoc}
     */
    public function addLabo(\hostoo\SanteBundle\Entity\OrdonnanceLabo $labo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addLabo', [$labo]);

        return parent::addLabo($labo);
    }

    /**
     * {@inheritDoc}
     */
    public function removeLabo(\hostoo\SanteBundle\Entity\OrdonnanceLabo $labo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeLabo', [$labo]);

        return parent::removeLabo($labo);
    }

    /**
     * {@inheritDoc}
     */
    public function getLabo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLabo', []);

        return parent::getLabo();
    }

}
