# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    hostoo_user.utilisateur.form.type:
        class: hostoo\UserBundle\Form\Type\UtilisateurType
        parent: fos_user.registration.form.type
        tags:
            - { name: form.type, alias: hostoo_user_utilisateur }
