<?php

namespace hostoo\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BanqueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanqueRepository extends EntityRepository
{
    public function depotMois($mois,$annee)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateops LIKE :datec')
            ->andWhere('a.mouvement LIKE :mvt')
            ->setParameter('datec',$annee.'-'.$mois.'%')
            ->setParameter('mvt','dépôt');;
        return $qb->getQuery()->getResult();
    }

    public function depotMoisTotal($mois,$annee)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.montant) AS total')
            ->where('a.dateops LIKE :datec')
            ->andWhere('a.mouvement LIKE :mvt')
            ->setParameter('datec',$annee.'-'.$mois.'%')
            ->setParameter('mvt','dépôt');
        return $qb->getQuery()->getResult();
    }

    public function depotJour($datejour)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateops LIKE :datec')
            ->andWhere('a.mouvement LIKE dépôt')
            ->setParameter('datec',$datejour.'%');
        return $qb->getQuery()->getResult();
    }


    public function retraitMois($mois,$annee)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateops LIKE :datec')
            ->andWhere('a.mouvement LIKE :mvt')
            ->setParameter('datec',$annee.'-'.$mois.'%')
            ->setParameter('mvt','retrait');
        return $qb->getQuery()->getResult();
    }

    public function retraitMoisTotal($mois,$annee)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.montant) AS total')
            ->where('a.dateops LIKE :datec')
            ->andWhere('a.mouvement LIKE :mvt')
            ->setParameter('datec',$annee.'-'.$mois.'%')
            ->setParameter('mvt','retrait');
        return $qb->getQuery()->getResult();
    }

    public function retraitJour($datejour)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateops LIKE :datec')
            ->andWhere('a.mouvement LIKE retrait')
            ->setParameter('datec',$datejour.'%');
        return $qb->getQuery()->getResult();
    }
}
