<?php

namespace hostoo\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BecaisseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BecaisseRepository extends EntityRepository
{
    public function depotInvestMois($mois,$annee)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateops LIKE :datec')
            ->andWhere('a.compte LIKE :cpte')
            ->setParameter('datec',$annee.'-'.$mois.'%')
            ->setParameter('cpte','investissement');;
        return $qb->getQuery()->getResult();
    }

    public function depotInvestMoisTotal($mois,$annee)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.montant) AS total')
            ->where('a.dateops LIKE :datec')
            ->andWhere('a.compte LIKE :cpte')
            ->setParameter('datec',$annee.'-'.$mois.'%')
            ->setParameter('cpte','investissement');
        return $qb->getQuery()->getResult();
    }

    public function depotInvestJour($datejour)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateops LIKE :datec')
            ->andWhere('a.compte LIKE :cpte')
            ->setParameter('datec',$datejour.'%')
            ->setParameter('cpte','investissement');
        return $qb->getQuery()->getResult();
    }
    public function depotRemMois($mois,$annee)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateops LIKE :datec')
            ->andWhere('a.compte LIKE :cpte')
            ->setParameter('datec',$annee.'-'.$mois.'%')
            ->setParameter('cpte','remise');
        return $qb->getQuery()->getResult();
    }

    public function depotRemMoisTotal($mois,$annee)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('SUM(a.montant) AS total')
            ->where('a.dateops LIKE :datec')
            ->andWhere('a.compte LIKE :cpte')
            ->setParameter('datec',$annee.'-'.$mois.'%')
            ->setParameter('cpte','remise');
        return $qb->getQuery()->getResult();
    }

    public function depotRemJour($datejour)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.dateops LIKE :datec')
            ->andWhere('a.compte LIKE :cpte')
            ->setParameter('datec',$datejour.'%')
            ->setParameter('cpte','remise');
        return $qb->getQuery()->getResult();
    }

}
