<?php

namespace hostoo\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HostooLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HostooLogRepository extends EntityRepository
{
    public function dejaConnecte($user)
    {
        $req=$this->createQueryBuilder('a');
        $req->join('a.utilisateur','us')
            ->where('us.id = :user')
            ->andWhere('a.temps LIKE :lelo AND a.evenement LIKE :mot')
            ->setParameter('user',$user)
            ->setParameter('lelo',date('Y-m-d').'%')
            ->setParameter('mot','Authentification')
        ;
        return $req->getQuery()->getOneOrNullResult();
    }
}
