<?php

namespace hostoo\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProprietaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProprietaireRepository extends EntityRepository
{
    public function societesDesPatients()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('a')
            ->where('a.etat = 1')
        ->orderBy('a.nom');
        return $qb->getQuery()->getResult();

    }
}
