<?php

namespace hostoo\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifRepository extends EntityRepository
{
    public function findArray($array,$conv)
    {
        $qb = $this->createQueryBuilder('u');

            $qb
            ->Where('u.actes IN (:array)')
            ->andWhere('u.convention = :conv')
            ->setParameter('array', $array)
            ->setParameter('conv',$conv);

            return $qb->getQuery()->getResult();


    }

    public function findEpisode($conv)
    {
        $qb = $this->createQueryBuilder('u');

        $qb
            ->Where('u.actes >1 and u.actes<=13')
            ->andWhere('u.convention = :conv')
            ->setParameter('conv',$conv);

        return $qb->getQuery()->getResult();


    }

    public function my($array,$conv)
    {
        $query = $this->_em->createQuery('SELECT a FROM hostooGestionBundle:Tarif a WHERE a.actes IN (:array) AND a.convention = :conv')
        ->setParameter('array', $array)
        ->setParameters('conv',$conv);
        $resultats = $query->getResult();
        return $resultats;
    }
}
