<?php

namespace hostoo\GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * VisaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisaRepository extends EntityRepository
{
    public function parDate($date)
    {
        $req=$this->createQueryBuilder('a');
        $req->where('a.datevisa LIKE :dv')
            ->setParameter('dv', $date.'%');
        return $req->getQuery()->getResult();
    }
}
