# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
services:
    redirect.after.login:
        class: hostoo\UserBundle\Redirection\AfterLoginRedirection
        arguments: [@router]

    redirect.after.logout:
        class: hostoo\UserBundle\Redirection\AfterLogoutRedirection
        arguments: [@router, @security.context]
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        hostoo\UserBundle\Entity\Utilisateur: sha512

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_RECEPTION:       [ROLE_RECEPTION, ROLE_CAISSIER, ROLE_INFIRMIER]
        ROLE_LABO:  [ROLE_LABORATOIRE]
        ROLE_IMG:  [ROLE_IMAGERIE]
        ROLE_PHAR:  [ROLE_PHARMACIE]
        ROLE_CAISSIER:  [ROLE_CAISSIER]
        ROLE_INFIRMIER:  [ROLE_INFIRMIER]
        ROLE_MEDECIN:  [ROLE_MEDECIN]
        ROLE_REPORT:  [ROLE_REPORT, ROLE_RECEPTION]
        ROLE_SUPER_ADMIN: [ROLE_RECEPTION, ROLE_LABO,ROLE_IMG, ROLE_PHAR, ROLE_DISPATCHER, ROLE_CAISSIER, ROLE_MEDECIN, ROLE_INFIRMIER, ROLE_ALLOWED_TO_SWITCH]
    providers:
        main:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_login:
            pattern: ^/login$
            anonymous: true
        main:
            pattern: ^/
            anonymous: false
            provider: main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                success_handler: redirect.after.login
            logout:
                path: fos_user_security_logout
                target: /login
                success_handler: redirect.after.logout
            remember_me:
                key: %secret%
    access_control:
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: http }
            - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
            #- { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/register, role: ROLE_SUPER_ADMIN }
            - { path: ^/resetting, role:  ROLE_SUPER_ADMIN }
            - { path: ^/admin, role:  ROLE_SUPER_ADMIN }
            #- { path: ^/, role:  ROLE_SUPER_ADMIN }
            - { path: ^/welcome, roles:  [ROLE_RECEPTION,ROLE_CAISSIER, ROLE_INFIRMIER] }
            - { path: ^/caisse, role: [ROLE_CAISSIER, ROLE_INFIRMIER] }
            - { path: ^/gestion, role: [ROLE_CAISSIER, ROLE_REPORT] }
            - { path: ^/banque, role: ROLE_CAISSIER }
            - { path: ^/dispatcher, role: [ROLE_DISPATCHER,ROLE_INFIRMIER] }
            - { path: ^/caisse, role: [ROLE_DISPATCHER,ROLE_INFIRMIER] }
            - { path: ^/nurse, role: [ROLE_DISPATCHER,ROLE_INFIRMIER] }
            - { path: ^/doctor, role: ROLE_MEDECIN }
            - { path: ^/laboratoire, role: ROLE_LABORATOIRE }
            - { path: ^/pharmacie, role: ROLE_PHARMACIE }
            - { path: ^/imagerie, role: ROLE_IMAGERIE }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
