# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    img_directory : '%kernel.root_dir%/../web/uploads/imageries'

services:
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }
    twig.extension.date:
        class: Twig_Extensions_Extension_Date
        tags:
            - { name: twig.extension }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    hostoo_user.utilisateur.form.type:
        class: hostoo\UserBundle\Form\Type\UtilisateurType
        parent: fos_user.registration.form.type
        tags:
            - { name: form.type, alias: hostoo_user_utilisateur }
#    hostoo.journal:
#        class: hostoo\SanteBundle\Journalisation\JournalisationListener
#        arguments: ["@doctrine.orm.entity_manager"]
    #hostoo.litoyi_listener:
        #class: hostoo\GestionBundle\Litoyi\LitoyiListener
        #arguments: ["2019-02-18"]
        #tags:
            #-  { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }