<?php

namespace hostoo\HospisBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HospitalisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospitalisationRepository extends EntityRepository
{
}
