<?php

namespace hostoo\PharmacieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CattheuraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CattheuraRepository extends EntityRepository
{
}
