<?php

namespace hostoo\PharmacieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends EntityRepository
{
    public function intervalleStock($datea,$dateb)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('a')
            ->where('a.datestock BETWEEN :datea AND :dateb')
            ->setParameter('datea',$datea)
            ->setParameter('dateb',$dateb)

        ;

        return $req->getQuery()->getResult();
    }
}
