<?php

namespace hostoo\PharmacieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StockTotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockTotRepository extends EntityRepository
{
}
