<?php

namespace hostoo\RDVBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RDVMedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RDVMedRepository extends EntityRepository
{
    public function trouverUnRDV($pat,$daterdv)
    {
        $qb=$this->createQueryBuilder('a');

        $qb
            ->where('a.patients = :pat')
            ->andWhere('a.daterdv LIKE :daterdv')
            ->setParameter('pat',$pat)
            ->setParameter('daterdv',$daterdv);
        return $qb->getQuery()->getOneOrNullResult();
    }
    public function trouverRDV($pat,$daterdv)
    {
        $qb=$this->createQueryBuilder('a');

        $qb
            ->where('a.patients = :pat')
            ->andWhere('a.daterdv > :daterdv')
            ->setParameter('pat',$pat)
            ->setParameter('daterdv',$daterdv)
            ->orderBy('a.daterdv','asc');
        return $qb->getQuery()->getResult();
    }

    public function trouver($pat)
    {
        $qb=$this->createQueryBuilder('a');

        $qb
            ->where('a.patients = :pat')
            ->andWhere('a.daterdv > :daterdv')
            ->setParameter('pat',$pat)
            ->setParameter('daterdv',date('Y-m-d'))
        ->orderBy('a.daterdv','asc');
        return $qb->getQuery()->getResult();
    }

    public function trouverToday()
    {
        $qb=$this->createQueryBuilder('a');

        $qb->where('a.daterdv LIKE :daterdv')
            ->setParameter('daterdv',date('Y-m-d'))
            ->orderBy('a.id','asc');
        return $qb->getQuery()->getResult();
    }
}
