<?php

namespace Proxies\__CG__\hostoo\SanteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Tarification extends \hostoo\SanteBundle\Entity\Tarification implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'designationacte', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'code', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'actes', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'categories', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'proforacte', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'facture', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'formule', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'valeur', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'tarif'];
        }

        return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'designationacte', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'code', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'actes', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'categories', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'proforacte', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'facture', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'formule', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'valeur', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Tarification' . "\0" . 'tarif'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Tarification $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDesignationacte($designationacte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDesignationacte', [$designationacte]);

        return parent::setDesignationacte($designationacte);
    }

    /**
     * {@inheritDoc}
     */
    public function getDesignationacte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDesignationacte', []);

        return parent::getDesignationacte();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrive($prive)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrive', [$prive]);

        return parent::setPrive($prive);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrive', []);

        return parent::getPrive();
    }

    /**
     * {@inheritDoc}
     */
    public function setGardejourferie($gardejourferie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGardejourferie', [$gardejourferie]);

        return parent::setGardejourferie($gardejourferie);
    }

    /**
     * {@inheritDoc}
     */
    public function getGardejourferie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGardejourferie', []);

        return parent::getGardejourferie();
    }

    /**
     * {@inheritDoc}
     */
    public function setConventionne($conventionne)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConventionne', [$conventionne]);

        return parent::setConventionne($conventionne);
    }

    /**
     * {@inheritDoc}
     */
    public function getConventionne()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConventionne', []);

        return parent::getConventionne();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategories(\hostoo\SanteBundle\Entity\Cattarifs $categories = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategories', [$categories]);

        return parent::setCategories($categories);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategories()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategories', []);

        return parent::getCategories();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacture(\hostoo\SanteBundle\Entity\Facture $facture = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacture', [$facture]);

        return parent::setFacture($facture);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacture', []);

        return parent::getFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function addFacture(\hostoo\SanteBundle\Entity\Facture $facture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFacture', [$facture]);

        return parent::addFacture($facture);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFacture(\hostoo\SanteBundle\Entity\Facture $facture)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFacture', [$facture]);

        return parent::removeFacture($facture);
    }

    /**
     * {@inheritDoc}
     */
    public function prixtarif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'prixtarif', []);

        return parent::prixtarif();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormule(\hostoo\SanteBundle\Entity\Formule $formule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormule', [$formule]);

        return parent::addFormule($formule);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormule(\hostoo\SanteBundle\Entity\Formule $formule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormule', [$formule]);

        return parent::removeFormule($formule);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormule', []);

        return parent::getFormule();
    }

    /**
     * {@inheritDoc}
     */
    public function addActe(\hostoo\GestionBundle\Entity\Tarif $actes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActe', [$actes]);

        return parent::addActe($actes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActe(\hostoo\GestionBundle\Entity\Tarif $actes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActe', [$actes]);

        return parent::removeActe($actes);
    }

    /**
     * {@inheritDoc}
     */
    public function getActes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActes', []);

        return parent::getActes();
    }

    /**
     * {@inheritDoc}
     */
    public function addProforacte(\hostoo\GestionBundle\Entity\FormuleTarificationProprietaire $proforacte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProforacte', [$proforacte]);

        return parent::addProforacte($proforacte);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProforacte(\hostoo\GestionBundle\Entity\FormuleTarificationProprietaire $proforacte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProforacte', [$proforacte]);

        return parent::removeProforacte($proforacte);
    }

    /**
     * {@inheritDoc}
     */
    public function getProforacte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProforacte', []);

        return parent::getProforacte();
    }

    /**
     * {@inheritDoc}
     */
    public function setValeur(\hostoo\SanteBundle\Entity\ValeurRef $valeur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValeur', [$valeur]);

        return parent::setValeur($valeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getValeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValeur', []);

        return parent::getValeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setTarif(\hostoo\GestionBundle\Entity\Tarif $tarif = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTarif', [$tarif]);

        return parent::setTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarif', []);

        return parent::getTarif();
    }

}
