<?php

namespace Proxies\__CG__\hostoo\GestionBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Convention extends \hostoo\GestionBundle\Entity\Convention implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'id', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'nomconvention', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'tconvention', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'dateconvention', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'formule', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'proprietaire', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'tarif'];
        }

        return ['__isInitialized__', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'id', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'nomconvention', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'tconvention', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'dateconvention', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'formule', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'proprietaire', '' . "\0" . 'hostoo\\GestionBundle\\Entity\\Convention' . "\0" . 'tarif'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Convention $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomconvention($nomconvention)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomconvention', [$nomconvention]);

        return parent::setNomconvention($nomconvention);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomconvention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomconvention', []);

        return parent::getNomconvention();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateconvention($dateconvention)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateconvention', [$dateconvention]);

        return parent::setDateconvention($dateconvention);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateconvention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateconvention', []);

        return parent::getDateconvention();
    }

    /**
     * {@inheritDoc}
     */
    public function addFormule(\hostoo\GestionBundle\Entity\Convention $formule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addFormule', [$formule]);

        return parent::addFormule($formule);
    }

    /**
     * {@inheritDoc}
     */
    public function removeFormule(\hostoo\GestionBundle\Entity\Convention $formule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeFormule', [$formule]);

        return parent::removeFormule($formule);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormule', []);

        return parent::getFormule();
    }

    /**
     * {@inheritDoc}
     */
    public function addTarif(\hostoo\GestionBundle\Entity\Tarif $tarif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addTarif', [$tarif]);

        return parent::addTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function removeTarif(\hostoo\GestionBundle\Entity\Tarif $tarif)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeTarif', [$tarif]);

        return parent::removeTarif($tarif);
    }

    /**
     * {@inheritDoc}
     */
    public function getTarif()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTarif', []);

        return parent::getTarif();
    }

    /**
     * {@inheritDoc}
     */
    public function setTconvention(\hostoo\GestionBundle\Entity\TConvention $tconvention = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTconvention', [$tconvention]);

        return parent::setTconvention($tconvention);
    }

    /**
     * {@inheritDoc}
     */
    public function getTconvention()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTconvention', []);

        return parent::getTconvention();
    }

    /**
     * {@inheritDoc}
     */
    public function addProprietaire(\hostoo\GestionBundle\Entity\Proprietaire $proprietaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProprietaire', [$proprietaire]);

        return parent::addProprietaire($proprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProprietaire(\hostoo\GestionBundle\Entity\Proprietaire $proprietaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProprietaire', [$proprietaire]);

        return parent::removeProprietaire($proprietaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getProprietaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProprietaire', []);

        return parent::getProprietaire();
    }

}
