<?php

namespace Proxies\__CG__\hostoo\SanteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class OrdonnanceImg extends \hostoo\SanteBundle\Entity\OrdonnanceImg implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'dateordo', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'valider', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'livre', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'actes', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'episode', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'hospitalisation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'resultats', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'facture', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'medecin'];
        }

        return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'dateordo', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'valider', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'livre', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'actes', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'episode', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'hospitalisation', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'resultats', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'facture', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\OrdonnanceImg' . "\0" . 'medecin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (OrdonnanceImg $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateordo($dateordo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateordo', [$dateordo]);

        return parent::setDateordo($dateordo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateordo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateordo', []);

        return parent::getDateordo();
    }

    /**
     * {@inheritDoc}
     */
    public function setEpisode(\hostoo\SanteBundle\Entity\Episode $episode = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEpisode', [$episode]);

        return parent::setEpisode($episode);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpisode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpisode', []);

        return parent::getEpisode();
    }

    /**
     * {@inheritDoc}
     */
    public function setValider($valider)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValider', [$valider]);

        return parent::setValider($valider);
    }

    /**
     * {@inheritDoc}
     */
    public function getValider()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValider', []);

        return parent::getValider();
    }

    /**
     * {@inheritDoc}
     */
    public function setLivre($livre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLivre', [$livre]);

        return parent::setLivre($livre);
    }

    /**
     * {@inheritDoc}
     */
    public function getLivre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLivre', []);

        return parent::getLivre();
    }

    /**
     * {@inheritDoc}
     */
    public function setFacture(\hostoo\SanteBundle\Entity\Facture $facture = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFacture', [$facture]);

        return parent::setFacture($facture);
    }

    /**
     * {@inheritDoc}
     */
    public function getFacture()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFacture', []);

        return parent::getFacture();
    }

    /**
     * {@inheritDoc}
     */
    public function addResultat(\hostoo\SanteBundle\Entity\ResultatsImg $resultats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addResultat', [$resultats]);

        return parent::addResultat($resultats);
    }

    /**
     * {@inheritDoc}
     */
    public function removeResultat(\hostoo\SanteBundle\Entity\ResultatsImg $resultats)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeResultat', [$resultats]);

        return parent::removeResultat($resultats);
    }

    /**
     * {@inheritDoc}
     */
    public function getResultats()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResultats', []);

        return parent::getResultats();
    }

    /**
     * {@inheritDoc}
     */
    public function afficherResultat($acte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'afficherResultat', [$acte]);

        return parent::afficherResultat($acte);
    }

    /**
     * {@inheritDoc}
     */
    public function examensEnAttente()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'examensEnAttente', []);

        return parent::examensEnAttente();
    }

    /**
     * {@inheritDoc}
     */
    public function examensEffectues()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'examensEffectues', []);

        return parent::examensEffectues();
    }

    /**
     * {@inheritDoc}
     */
    public function Etat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'Etat', []);

        return parent::Etat();
    }

    /**
     * {@inheritDoc}
     */
    public function setMedecin(\hostoo\UserBundle\Entity\Utilisateur $medecin = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMedecin', [$medecin]);

        return parent::setMedecin($medecin);
    }

    /**
     * {@inheritDoc}
     */
    public function getMedecin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMedecin', []);

        return parent::getMedecin();
    }

    /**
     * {@inheritDoc}
     */
    public function addActe(\hostoo\SanteBundle\Entity\Tarification $actes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addActe', [$actes]);

        return parent::addActe($actes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeActe(\hostoo\SanteBundle\Entity\Tarification $actes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeActe', [$actes]);

        return parent::removeActe($actes);
    }

    /**
     * {@inheritDoc}
     */
    public function getActes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActes', []);

        return parent::getActes();
    }

    /**
     * {@inheritDoc}
     */
    public function setHospitalisation(\hostoo\HospisBundle\Entity\Hospitalisation $hospitalisation = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHospitalisation', [$hospitalisation]);

        return parent::setHospitalisation($hospitalisation);
    }

    /**
     * {@inheritDoc}
     */
    public function getHospitalisation()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHospitalisation', []);

        return parent::getHospitalisation();
    }

}
