<?php

namespace Proxies\__CG__\hostoo\SanteBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Patient extends \hostoo\SanteBundle\Entity\Patient implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'nom', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'postnom', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'prenom', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'sexe', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'datenaissance', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'nationalite', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'adresse', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'telephone1', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'telephone2', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'numerodossier', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'societe', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'formule', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'episode', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'dependants', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'dateenr', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'datemod', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'rendez', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'madependance'];
        }

        return ['__isInitialized__', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'id', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'nom', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'postnom', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'prenom', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'sexe', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'datenaissance', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'nationalite', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'adresse', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'telephone1', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'telephone2', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'numerodossier', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'societe', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'formule', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'episode', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'dependants', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'dateenr', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'datemod', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'rendez', '' . "\0" . 'hostoo\\SanteBundle\\Entity\\Patient' . "\0" . 'madependance'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Patient $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', [$nom]);

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', []);

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPostnom($postnom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPostnom', [$postnom]);

        return parent::setPostnom($postnom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPostnom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPostnom', []);

        return parent::getPostnom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', [$prenom]);

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', []);

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setSexe($sexe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSexe', [$sexe]);

        return parent::setSexe($sexe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSexe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSexe', []);

        return parent::getSexe();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenaissance($datenaissance)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenaissance', [$datenaissance]);

        return parent::setDatenaissance($datenaissance);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenaissance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenaissance', []);

        return parent::getDatenaissance();
    }

    /**
     * {@inheritDoc}
     */
    public function setNationalite($nationalite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNationalite', [$nationalite]);

        return parent::setNationalite($nationalite);
    }

    /**
     * {@inheritDoc}
     */
    public function getNationalite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNationalite', []);

        return parent::getNationalite();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone1($telephone1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone1', [$telephone1]);

        return parent::setTelephone1($telephone1);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone1', []);

        return parent::getTelephone1();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone2($telephone2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone2', [$telephone2]);

        return parent::setTelephone2($telephone2);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone2', []);

        return parent::getTelephone2();
    }

    /**
     * {@inheritDoc}
     */
    public function addEpisode(\hostoo\SanteBundle\Entity\Episode $episode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addEpisode', [$episode]);

        return parent::addEpisode($episode);
    }

    /**
     * {@inheritDoc}
     */
    public function removeEpisode(\hostoo\SanteBundle\Entity\Episode $episode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeEpisode', [$episode]);

        return parent::removeEpisode($episode);
    }

    /**
     * {@inheritDoc}
     */
    public function getEpisode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEpisode', []);

        return parent::getEpisode();
    }

    /**
     * {@inheritDoc}
     */
    public function addDependant(\hostoo\SanteBundle\Entity\Dependant $dependants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDependant', [$dependants]);

        return parent::addDependant($dependants);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDependant(\hostoo\SanteBundle\Entity\Dependant $dependants)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDependant', [$dependants]);

        return parent::removeDependant($dependants);
    }

    /**
     * {@inheritDoc}
     */
    public function getDependants()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDependants', []);

        return parent::getDependants();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateenr($dateenr)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateenr', [$dateenr]);

        return parent::setDateenr($dateenr);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateenr()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateenr', []);

        return parent::getDateenr();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatemod($datemod)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatemod', [$datemod]);

        return parent::setDatemod($datemod);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatemod()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatemod', []);

        return parent::getDatemod();
    }

    /**
     * {@inheritDoc}
     */
    public function setSociete(\hostoo\GestionBundle\Entity\Proprietaire $societe = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSociete', [$societe]);

        return parent::setSociete($societe);
    }

    /**
     * {@inheritDoc}
     */
    public function getSociete()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSociete', []);

        return parent::getSociete();
    }

    /**
     * {@inheritDoc}
     */
    public function addRendez(\hostoo\RDVBundle\Entity\RDVMed $rendez)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addRendez', [$rendez]);

        return parent::addRendez($rendez);
    }

    /**
     * {@inheritDoc}
     */
    public function removeRendez(\hostoo\RDVBundle\Entity\RDVMed $rendez)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeRendez', [$rendez]);

        return parent::removeRendez($rendez);
    }

    /**
     * {@inheritDoc}
     */
    public function getRendez()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRendez', []);

        return parent::getRendez();
    }

    /**
     * {@inheritDoc}
     */
    public function setFormule(\hostoo\SanteBundle\Entity\Formule $formule = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFormule', [$formule]);

        return parent::setFormule($formule);
    }

    /**
     * {@inheritDoc}
     */
    public function getFormule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFormule', []);

        return parent::getFormule();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumerodossier($numerodossier)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumerodossier', [$numerodossier]);

        return parent::setNumerodossier($numerodossier);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumerodossier()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumerodossier', []);

        return parent::getNumerodossier();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function age()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'age', []);

        return parent::age();
    }

    /**
     * {@inheritDoc}
     */
    public function setMadependance(\hostoo\SanteBundle\Entity\Dependant $madependance = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMadependance', [$madependance]);

        return parent::setMadependance($madependance);
    }

    /**
     * {@inheritDoc}
     */
    public function getMadependance()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMadependance', []);

        return parent::getMadependance();
    }

}
