hostoo_sante_ajoutercte:
    path: /ajoute_acte/{id}
    defaults: { _controller: hostooSanteBundle:Episode:ajouterActe }

hostoo_sante_suppcte:
    path: /supprimer_acte/{id}
    defaults: { _controller: hostooSanteBundle:Episode:supprimerActe }

hostoo_sante_ajouterctelbo:
    path: /ajoute_actelbo/{id}
    defaults: { _controller: hostooSanteBundle:Episode:ajouterActelbo }

hostoo_sante_suppctelbo:
    path: /supprimer_actelbo/{id}
    defaults: { _controller: hostooSanteBundle:Episode:supprimerActelbo }

hostoo_sante_factureactes:
    path: /factures_actes/{id}
    defaults: { _controller: hostooSanteBundle:Episode:factureActes }

hostoo_sante_resetactes:
    path: /reset_actes/{id}
    defaults: { _controller: hostooSanteBundle:Episode:resetActes }

hostoo_sante_attrrdv:
    path: /attribuer-rdv/{id}
    defaults: { _controller: hostooSanteBundle:RDV:attribuerRDV }

hostoo_sante_tousrdv:
    path: /tous-rdvs
    defaults: { _controller: hostooSanteBundle:RDV:tousRDV }

hostoo_service_ajouter:
    path: /ajouter-service
    defaults: { _controller: hostooSanteBundle:Service:ajouterService }

hostoo_sante_lesactesdupatientparepisode:
    path:     /les_actes_du_patient/{id}
    defaults: { _controller: hostooSanteBundle:Episode:voirActesEpisode }
    requirements:
        id: \d+