hostoo_labo_dash:
    path: /dash
    defaults: { _controller: hostooSanteBundle:Laboratoire:index }

ajouter_resultat:
    path: /ajouter-resultat/{id}
    defaults: { _controller: hostooSanteBundle:Laboratoire:ajouterResultat }
valider_resultat:
    path: /valider-resultat/{id}
    defaults: { _controller: hostooSanteBundle:Laboratoire:validerResultat }