# caisse
hostoo_sante_listeactes:
    path: /liste-des-actes
    defaults: { _controller: hostooSanteBundle:Caisse:listeActes }

caisse_medecins:
    path: /liste-medecins
    defaults: { _controller: hostooGestionBundle:Gestion:lesMedecins }

hostoo_sante_listeactest:
    path: /liste-des-actes-toutes
    defaults: { _controller: hostooSanteBundle:Caisse:listeActesToutes }

hostoo_sante_valideracte:
    path: /valider-des-actes/{id}
    defaults: { _controller: hostooSanteBundle:Caisse:validerActe }

hostoo_sante_soldeacte:
    path: /solde-acte/{acte}
    defaults: { _controller: hostooSanteBundle:Caisse:soldeActe }

hostoo_sante_bscaisse:
    path: /cree-bon-de-sortie-caisse
    defaults: { _controller: hostooSanteBundle:Caisse:creeBS }

hostoo_sante_bs:
    path: /lire-bs/{id}
    defaults: { _controller: hostooSanteBundle:Caisse:lireBS }

hostoo_sante_bsliste:
    path: /liste-bs
    defaults: { _controller: hostooSanteBundle:Caisse:listeBS }

hostoo_caisse_dash:
    path: /dash-bs
    defaults: { _controller: hostooSanteBundle:Caisse:dash }

hostoo_caisse_mettredevise:
    path: /mettredevise
    defaults: { _controller: hostooSanteBundle:Caisse:mettreDevise }

hostoo_caisse_taux:
    path: /nouveauTaux
    defaults: { _controller: hostooSanteBundle:Caisse:nouveauTaux }
hostoo_caisse_tb:
    path: /caisseTB
    defaults: { _controller: hostooSanteBundle:TB:caisseTB }

print_facture:
    path: /print-facture/{id}
    defaults: { _controller: hostooSanteBundle:Caisse:printFacture }
lescomissions_med:
    path: /comissions-med/{medecin}
    defaults: { _controller: hostooSanteBundle:Caisse:lesComissions }

print_som:
    path: /print-som/
    defaults: { _controller: hostooSanteBundle:Caisse:sommeBSusd }

rapport_du_mois:
    path: /rapport
    defaults: { _controller: hostooGestionBundle:rapportCaisseJr:moisRapport }
