<?php

namespace hostoo\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UtilisateurRepository extends EntityRepository
{
    public function lesmedecins()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.roles LIKE :spec')
        ->setParameter('spec','%ROLE_MEDECIN%');

        return $qb;
    }

    public function lesmedecinsListe()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->where('a.roles LIKE :spec')
            ->setParameter('spec','%ROLE_MEDECIN%');

        return $qb->getQuery()->getResult();
    }

    public function lesordonnancesLabo($user)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('COUNT(lesactes) as nbr')
            ->join('a.episode','e')
            ->join('e.ordonnancelabo','o')
            ->join('o.actesl','lesactes')
            ->where('a.id = :user')
            ->setParameter('user',$user)
        ;
        return $req->getQuery()->getSingleResult();

    }

    public function lesordonnancesImg($user)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('COUNT(lesactes) as nbr')
            ->join('a.episode','e')
            ->join('e.ordonnanceimg','o')
            ->join('o.actesi','lesactes')
            ->where('a.id = :user')
            ->setParameter('user',$user)
        ;
        return $req->getQuery()->getSingleResult();

    }
}
