<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Cim10Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Cim10Repository extends EntityRepository
{
    public function trouverPathologie($nom)
    {
        $qb=$this->createQueryBuilder('u');
        $qb->select('u')
            ->where('u.pathologie LIKE :pathologie')
            ->setParameter('pathologie',$nom.'%');
        return $qb->getQuery()->getResult();
    }
}

