<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ListeSoinsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ListeSoinsRepository extends EntityRepository
{
    public function listeDesSoinsToday($datesoi)
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('a')
            ->where('a.datesoins LIKE :mydate')
        ->setParameter('mydate',$datesoi.'%')
        ->orderBy('a.id');
        return $qb->getQuery()->getResult();

    }
}
