<?php

namespace hostoo\SanteBundle\Repository;

/**
 * ParenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParenteRepository extends \Doctrine\ORM\EntityRepository
{
}
