<?php

namespace hostoo\SanteBundle\Repository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends \Doctrine\ORM\EntityRepository
{
    public function nombresConventionnes()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('COUNT(a) as NbrePatients')
            ->join('a.societe','b')
            ->join('b.convention','c')
            ->where('c.id = 1 and b.etat = 1');
        return $qb->getQuery()->getResult();
    }

    public function nombresPrives()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('COUNT(a) as NbrePatients')
            ->join('a.societe','b')
            ->join('b.convention','c')
            ->where('c.id = 2  and b.etat = 1');
        return $qb->getQuery()->getResult();
    }

    public function nbrGroupesSocietesPatients()
    {
        $qb=$this->createQueryBuilder('a');
        $qb->select('COUNT(a) as NbrePatients')
            ->join('a.societe','s')
            ->where('s.etat = 1')
            ->groupBy('a.societe');
        return $qb->getQuery()->getResult();
    }

    public function recherchePatient($motcle)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('a')
            ->join('a.societe','soc')
            ->where('a.nom LIKE :motcle OR a.prenom LIKE :motcle')
            ->setParameter('motcle','%'.$motcle.'%')
            ->andWhere('soc.etat = 1');
        return $req->getQuery()->getResult();
    }

    public function patientsActifs()
    {
     $req=$this->createQueryBuilder('a');
     $req->select('a')
        ->join('a.societe','soc')
        ->where('soc.etat = 1 ');
        return $req->getQuery()->getResult();
    }

    public function patientsParFormuleActifs($mysoc)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('a')
            ->join('a.formule','formule')
            ->join('a.societe','soc')
            ->where('formule.id= :mysoc')
            ->andWhere('soc.etat= 1')
            ->setParameter('mysoc',$mysoc);
        return $req->getQuery()->getResult();
    }
    public function patientsParSocieteActifs($mysoc)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('a')
            ->join('a.societe','soc')
            ->where('soc.etat = 1 ')
            ->andWhere('soc.id= :mysoc')
            ->setParameter('mysoc',$mysoc);
        return $req->getQuery()->getResult();
    }
}
