<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PosologieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosologieRepository extends EntityRepository
{
    public function consoStock($datea)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('a')
            ->join('a.ordonnance','ord')
            ->where('ord.dateordo LIKE :datea')
            ->setParameter('datea',$datea.'%')
        ;

        return $req->getQuery()->getResult();
    }
    public function intervalleStock($datea,$dateb)
    {
        $req=$this->createQueryBuilder('a');
        $req->select('a')
            ->join('a.ordonnance','ord')
            ->where('ord.dateordo BETWEEN :datea AND :dateb')
            ->setParameter('datea',$datea.' 00:00:00')
            ->setParameter('dateb',$dateb.' 23:59:59')

        ;

        return $req->getQuery()->getResult();
    }
}
