<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RdvpatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdvPatientRepository extends EntityRepository
{
    public function rdvMedparLaDate($date)
    {
        $qb=$this->createQueryBuilder('u');
        $qb->select('u')
            ->join('u.rdv','d')
            ->where('u.daterdv = :dateR and u.valid=1')
            //->andWhere('d.medecin=:med')
            ->orderBy('u.id ','desc')
            ->setParameter('dateR',$date);
            //->setParameter('med',$med);
        return $qb->getQuery()->getResult();
    }
    public function rdvMed($med)
    {
        $qb=$this->createQueryBuilder('u');
        $qb->select('u')
            ->join('u.rdv','d')
            ->where('u.valid=1')
            ->andWhere('d.medecin=:med')
            ->orderBy('u.id ','desc')
        ->setParameter('med',$med);
        return $qb->getQuery()->getResult();
    }

    public function rdvTest($episode)
    {
        $qb=$this->createQueryBuilder('u');
        $qb->where('u.episode=:med')
            ->setParameter('med',$episode);
        return $qb->getQuery()->getOneOrNullResult();
    }
}
