<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * RdvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RdvRepository extends EntityRepository
{
    public function parLaDate($date)
    {
        $qb=$this->createQueryBuilder('u');
        $qb->select('u')
            ->where('u.daterdv = :dateR')
            ->orderBy('u.id ','desc')
            ->setParameter('dateR',$date);
            return $qb->getQuery()->getResult();
    }

    public function rdvMedparLaDate($med,$date)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->join('u.RDVspatients','p')
            ->where('u.daterdv = :dateR AND p.recu=:recu')
            ->andWhere('u.medecin=:med AND p.valid= :val')
            ->setParameter('recu',0)
            ->setParameter('val',1)
            ->setParameter('dateR',$date)
            ->setParameter('med', $med);
        //var_dump($qb->getQuery()->getSingleResult()); die('requete');
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function rdvMedparLaDateOk($med,$date)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->join('u.RDVspatients','p')
            ->where('u.daterdv = :dateR AND p.recu=:recu')
            ->andWhere('u.medecin=:med AND p.valid= :val')
            ->setParameter('recu',1)
            ->setParameter('val',1)
            ->setParameter('dateR',$date)
            ->setParameter('med', $med);
        //var_dump($qb->getQuery()->getSingleResult()); die('requete');
        return $qb->getQuery()->getOneOrNullResult();
    }

    public function rdvMed($med)
    {
        $qb = $this->createQueryBuilder('u');
        $qb->select('u')
            ->where('u.medecin=:med')
            ->setParameter('med', $med);
        //var_dump($qb->getQuery()->getSingleResult()); die('requete');
        return $qb->getQuery()->getResult();
    }
}
