<?php

namespace hostoo\SanteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TarificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarificationRepository extends EntityRepository
{
    public function findArray($array)
    {
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->Where('u.id IN (:array)')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }

    public function ActesLabo()
    {

        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->join('u.categories','c')
            ->Where('c.id >= 18');
        return $qb->getQuery()->getResult();
    }

    public function ActesImg()
    {
        $array=[13,14];
        $qb = $this->createQueryBuilder('u')
            ->Select('u')
            ->join('u.categories','c')
            ->Where('c.id IN (:array)')
            ->setParameter('array', $array);
        return $qb->getQuery()->getResult();
    }
}
