rdvmed_index:
    path:     /
    defaults: { _controller: "hostooRDVBundle:RDVMed:index" }
    methods:  GET

rdvmed_show_today:
    path:     /rdv-aujourdhui
    defaults: { _controller: "hostooRDVBundle:RDVMed:LesRDVToday" }
    methods:  GET

rdvmed_show_tout:
    path:     /rdv-tout
    defaults: { _controller: "hostooRDVBundle:RDVMed:LesRDVTout" }
    methods:  GET
rdvmed_list:
    path:     /list-rdv/{pat}
    defaults: { _controller: "hostooRDVBundle:RDVMed:list" }
    methods:  GET
rdvmed_show:
    path:     /{id}/show
    defaults: { _controller: "hostooRDVBundle:RDVMed:show" }
    methods:  GET

rdvmed_new:
    path:     /new/{id}
    defaults: { _controller: "hostooRDVBundle:RDVMed:new" }
    methods:  POST

rdvmed_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooRDVBundle:RDVMed:edit" }
    methods:  [GET, POST]

rdvmed_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooRDVBundle:RDVMed:delete" }
    methods:  DELETE
