becaisse_index:
    path:     /
    defaults: { _controller: "hostooGestionBundle:Becaisse:index" }
    methods:  GET

becaisse_show:
    path:     /{id}/show
    defaults: { _controller: "hostooGestionBundle:Becaisse:show" }
    methods:  GET

becaisse_new:
    path:     /new
    defaults: { _controller: "hostooGestionBundle:Becaisse:new" }
    methods:  [GET, POST]

becaisse_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooGestionBundle:Becaisse:edit" }
    methods:  [GET, POST]

becaisse_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooGestionBundle:Becaisse:delete" }
    methods:  DELETE
