lesbanques_index:
    path:     /
    defaults: { _controller: "hostooGestionBundle:LesBanques:index" }
    methods:  GET

lesbanques_show:
    path:     /{id}/show
    defaults: { _controller: "hostooGestionBundle:LesBanques:show" }
    methods:  GET

lesbanques_new:
    path:     /new
    defaults: { _controller: "hostooGestionBundle:LesBanques:new" }
    methods:  [GET, POST]

lesbanques_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooGestionBundle:LesBanques:edit" }
    methods:  [GET, POST]

lesbanques_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooGestionBundle:LesBanques:delete" }
    methods:  DELETE
