banque_index:
    path:     /
    defaults: { _controller: "hostooGestionBundle:Banque:index" }
    methods:  GET

banque_show:
    path:     /{id}/show
    defaults: { _controller: "hostooGestionBundle:Banque:show" }
    methods:  GET

banque_new:
    path:     /new
    defaults: { _controller: "hostooGestionBundle:Banque:new" }
    methods:  [GET, POST]

banque_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooGestionBundle:Banque:edit" }
    methods:  [GET, POST]

banque_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooGestionBundle:Banque:delete" }
    methods:  DELETE
