rapportcaissejr_index:
    path:     /
    defaults: { _controller: "hostooGestionBundle:rapportCaisseJr:index" }
    methods:  GET

rapportcaissejr_show:
    path:     /{id}/show
    defaults: { _controller: "hostooGestionBundle:rapportCaisseJr:show" }
    methods:  GET

rapportcaissejr_new:
    path:     /new
    defaults: { _controller: "hostooGestionBundle:rapportCaisseJr:new" }
    methods:  [GET, POST]

rapportcaissejr_edit:
    path:     /{id}/edit
    defaults: { _controller: "hostooGestionBundle:rapportCaisseJr:edit" }
    methods:  [GET, POST]

rapportcaissejr_delete:
    path:     /{id}/delete
    defaults: { _controller: "hostooGestionBundle:rapportCaisseJr:delete" }
    methods:  DELETE
