hostoo_user_homepage:
    path:     /
    defaults: { _controller: hostooUserBundle:Default:listeUsers }

hostoo_user_creeruser:
    path:     /creeuser
    defaults: { _controller: hostooUserBundle:Default:creeUser }

hostoo_user_edituser:
    path:     /edituser/{id}
    defaults: { _controller: hostooUserBundle:Default:editUser }